In [21]:
import random
import json
import pickle
import numpy as np

import nltk
from nltk.stem import WordNetLemmatizer
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation, Dropout
from tensorflow.keras.optimizers import SGD
nltk.download('punkt')
nltk.download('wordnet')
nltk.download('omw-1.4')



[nltk_data] Downloading package punkt to /Users/timbleuze/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/timbleuze/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     /Users/timbleuze/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


True

In [22]:
lemmatizer = WordNetLemmatizer()
intents = json.loads(open('test.json').read())

In [23]:
words = []
classes = []
documents = []
ignore_letters = ['?', '!', '.', ',']

In [24]:
for intent in intents['intents']:
    for pattern in intent['patterns']:
        world_list = nltk.word_tokenize(pattern)
        words.extend(world_list)
        documents.append((world_list, intent['tag']))
        if intent['tag'] not in classes:
            classes.append(intent['tag'])
print(documents)

[(['Hi'], 'greeting'), (['How', 'are', 'you'], 'greeting'), (['Is', 'anyone', 'there', '?'], 'greeting'), (['Hello'], 'greeting'), (['Good', 'day'], 'greeting'), (['Whats', 'up'], 'greeting'), (['How', 'do', 'you', 'do'], 'greeting'), (['Nice', 'to', 'meet', 'you'], 'greeting'), (['Pleased', 'to', 'meet', 'you'], 'greeting'), (['How', 'have', 'you', 'been'], 'greeting'), (['Good', 'Morning'], 'greeting'), (['Good', 'Afternoon'], 'greeting'), (['Good', 'Evening'], 'greeting'), (['Dear', 'Sir', 'or', 'Madam'], 'greeting'), (['To', 'Whom', 'It', 'May', 'Concern'], 'greeting'), (['To', 'the', 'Hiring', 'Manager'], 'greeting'), (['Dear', 'Mr', 'X'], 'greeting'), (['Mrs', 'X'], 'greeting'), (['Ms', 'X'], 'greeting'), (['Miss', 'X'], 'greeting'), (['Prof', 'X'], 'greeting'), (['Dr', 'X'], 'greeting'), (['Hello'], 'greeting'), (['Hi'], 'greeting'), (['Hey'], 'greeting'), (['Morning'], 'greeting'), (['Afternoon'], 'greeting'), (['Evening'], 'greeting'), (['How', 'are', 'you', 'doing'], 'greetin

In [25]:
words = [lemmatizer.lemmatize(str(word)) for word in words if word not in ignore_letters]
words = sorted(set(words))

classes = sorted(set(classes))

In [26]:
pickle.dump(words, open('words.pkl', 'wb'))
pickle.dump(classes, open('classes.pkl', 'wb'))

In [27]:
tarining = []
output_empty = [0] * len(classes)

for document in documents:
    bag = []
    word_patterns = document[0]
    word_patterns = [lemmatizer.lemmatize(word.lower()) for word in word_patterns]
    for word in words:
        bag.append(1) if word in word_patterns else bag.append(0)
    
    output_row = list(output_empty)
    output_row[classes.index(document[1])] = 1
    tarining.append([bag, output_row])
random.shuffle(tarining)
tarining = np.array(tarining)
print(tarining)


[[list([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0])
  list([0, 0, 0, 0, 0, 0, 1])]
 [list([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
  list([0, 1, 0, 0, 0, 0, 0])]
 [list([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

/var/folders/82/b57kstbn303cy1b030wlchqm0000gn/T/ipykernel_2820/42574386.py:15: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  tarining = np.array(tarining)


In [28]:
train_x = list(tarining[:,0])
train_y = list(tarining[:,1])
print(type(train_x))


<class 'list'>


In [29]:
print(len(train_y))
print(len(train_x))

82
82


In [30]:
model = Sequential()
model.add(Dense(128, input_shape=(len(train_x[0]),), activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(len(train_y[0]), activation='softmax'))

In [31]:
sgd = SGD(lr=0.01, decay=1e-6,momentum=0.9, nesterov=True)
model.compile(loss='categorical_crossentropy', optimizer=sgd, metrics=['accuracy'])

In [32]:
print(np.array(train_x))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [35]:
x = model.fit(np.array(train_x), np.array(train_y), epochs=200, batch_size=5)

Epoch 1/200
17/17 [==============================] - 0s 539us/step - loss: 0.1589 - accuracy: 0.9756
Epoch 2/200
17/17 [==============================] - 0s 399us/step - loss: 0.0943 - accuracy: 0.9878
Epoch 3/200
17/17 [==============================] - 0s 406us/step - loss: 0.0653 - accuracy: 0.9878
Epoch 4/200
17/17 [==============================] - 0s 355us/step - loss: 0.1136 - accuracy: 0.9634
Epoch 5/200
17/17 [==============================] - 0s 370us/step - loss: 0.0476 - accuracy: 0.9878
Epoch 6/200
17/17 [==============================] - 0s 390us/step - loss: 0.0771 - accuracy: 0.9878
Epoch 7/200
17/17 [==============================] - 0s 339us/step - loss: 0.0837 - accuracy: 0.9878
Epoch 8/200
17/17 [==============================] - 0s 392us/step - loss: 0.0728 - accuracy: 0.9878
Epoch 9/200
17/17 [==============================] - 0s 353us/step - loss: 0.0803 - accuracy: 0.9878
Epoch 10/200
17/17 [==============================] - 0s 406us/step - loss: 0.0616 - accura

In [34]:
model.save('botV1.h5', x)